language: r
r:
  - oldrel
  - release
  - devel
cache: packages
addons:
  apt:
    packages:
    - libgmp3-dev
r_build_args:
r_check_args:
r_packages: rmarkdown
# warnings_are_errors: false
after_success:
  - Rscript -e 'goodpractice::gp(checks = c("lintr_assignment_linter", "truefalse_not_tf", "rcmdcheck_partial_argument_match"))'
  - Rscript -e 'covr::codecov()'
notifications:
  email:
    on_success: never
    on_failure: never
  slack: 
    on_success: never
    on_failure: r-pavo:J07z1Fy6Txm0PBcHwVk782OD
