language: r
cache: packages
addons:
  apt:
    packages:
    - libgmp3-dev
r_build_args: 
r_check_args: 
# warnings_are_errors: false
notifications:
  email:
    on_success: never
    on_failure: never
  slack: r-pavo:J07z1Fy6Txm0PBcHwVk782OD
