language: r
cache: packages
addons:
  apt:
    packages:
    - libgmp3-dev
r_build_args: --no-build-vignettes
r_check_args: --no-manual
notifications:
  email:
    on_success: change
    on_failure: change
  slack: r-pavo:J07z1Fy6Txm0PBcHwVk782OD
  
