on:
  push:
    branches: master

name: pkgdown

jobs:
  pkgdown:
    env:
      # prevent rgl issues because no X11 display is available
      RGL_USE_NULL: true
      DISPLAY: 99 # for rgl
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew cask install xquartz
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("r-lib/pkgdown")
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL .
      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
